"""
    A UNIQUE COLLECTION OF ELEMENTS
        #ID_NO
"""

SET_=()
# ALL THE MEMBERS OF CLASS24 ARE UNIQUE
CLASS24={"AMADOU","MOHAMED","SAMBA","AMADOU"}
PRINT(TYPE(CLASS24))
PRINT(CLASS24)

# ALL THE MEMBERS OF CLASS24 ARE UNIQUE
CLASS25={"JOHN","DOE","JANE","JOHN"}
PRINT(TYPE(CLASS25))
PRINT(CLASS25)

PRINT("=====================================================================================")

# WHAT MEMBERS ARE BOTH IN CLASS24 AND CLASS25? INTERSECTION (COMMON AREA)
INTERSECTION=CLASS24 & CLASS25
INTERSECTION2=CLASS24.INTERSECTION(CLASS25)
PRINT(INTERSECTION)

# WHAT MEMBERS ARE IN CLASS24 AND NOT IN CLASS25? DIFFERENCE 
DIFFERENCE_24_25=CLASS24 - CLASS25
DIFFERENCE_24_25=CLASS24.DIFFERENCE(CLASS25)
PRINT(DIFFERENCE_24_25)

#WHAT MEMBERS ARES IN CLASS25 AND NOT IN CLASS24? DIFFERENCE
DIFFERENCE_25_24=CLASS25 - CLASS24
DIFFERENCE_25_24=CLASS25.DIFFERENCE(CLASS24)
PRINT(DIFFERENCE_25_24)

# WHAT MEMBERS ARE IN CLASS24 OR CLASS25? UNION
UNION_24_25=CLASS24 | CLASS25
UNION_24_25=CLASS24.UNION(CLASS25)
PRINT(UNION_24_25)